----Retrieve a list of all orders along with customer information:
SELECT
    Orders.OrderID,
    Customers.CustomerID,
    Customers.FirstName,
    Customers.LastName,
    Customers.Email,
    Customers.Phone
FROM
    Orders
JOIN
    Customers ON Orders.CustomerID = Customers.CustomerID;

    
--2 Find the total revenue generated by each electronic gadget product:
SELECT
    Products.ProductName,
    SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
FROM
    OrderDetails
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY
    Products.ProductName;

--3 List all customers who have made at least one purchase:

SELECT DISTINCT
    Customers.CustomerID,
    Customers.FirstName,
    Customers.LastName,
    Customers.Email,
    Customers.Phone
FROM
    Customers
JOIN
    Orders ON Customers.CustomerID = Orders.CustomerID;

--4 Find the most popular electronic gadget (highest total quantity ordered):


SELECT TOP 1
    Products.ProductName,
    SUM(OrderDetails.Quantity) AS TotalQuantityOrdered
FROM
    OrderDetails
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY
    Products.ProductName
ORDER BY
    TotalQuantityOrdered DESC;

--5 Retrieve a list of electronic gadgets along with their corresponding categories:

--6 Calculate the average order value for each customer:

SELECT
    Customers.CustomerID,
    Customers.FirstName,
    Customers.LastName,
    AVG(OrderDetails.Quantity * Products.Price) AS AverageOrderValue
FROM
    Customers
JOIN
    Orders ON Customers.CustomerID = Orders.CustomerID
JOIN
    OrderDetails ON Orders.OrderID = OrderDetails.OrderID
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY
    Customers.CustomerID, Customers.FirstName, Customers.LastName;

--7 Find the order with the highest total revenue:

SELECT TOP 1
    Orders.OrderID,
    Customers.CustomerID,
    Customers.FirstName,
    Customers.LastName,
    SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
FROM
    Orders
JOIN
    Customers ON Orders.CustomerID = Customers.CustomerID
JOIN
    OrderDetails ON Orders.OrderID = OrderDetails.OrderID
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY
    Orders.OrderID, Customers.CustomerID, Customers.FirstName, Customers.LastName
ORDER BY
    TotalRevenue DESC;

--8 List electronic gadgets and the number of times each product has been ordered:

SELECT
    Products.ProductName,
    COUNT(OrderDetails.OrderID) AS NumberOfOrders
FROM
    Products
LEFT JOIN
    OrderDetails ON Products.ProductID = OrderDetails.ProductID
GROUP BY
    Products.ProductName;


	--9 Find customers who have purchased a specific electronic gadget product:

	DECLARE @ProductName VARCHAR(255) = 'Tablet';

SELECT
    Customers.CustomerID,
    Customers.FirstName,
    Customers.LastName,
    Customers.Email,
    Customers.Phone
FROM
    Customers
JOIN
    Orders ON Customers.CustomerID = Orders.CustomerID
JOIN
    OrderDetails ON Orders.OrderID = OrderDetails.OrderID
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
WHERE
    Products.ProductName = @ProductName;

	--10 Calculate the total revenue generated by all orders placed within a specific time period:

	DECLARE @StartDate DATE = '2023-01-02';
DECLARE @EndDate DATE = '2023-01-07';

SELECT
    SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
FROM
    Orders
JOIN
    OrderDetails ON Orders.OrderID = OrderDetails.OrderID
JOIN
    Products ON OrderDetails.ProductID = Products.ProductID
WHERE
    Orders.OrderDate BETWEEN @StartDate AND @EndDate;